[package]
name = "iron-csrf"
version = "0.0.3"
authors = ["heartsucker <heartsucker@autistici.org>"]
description = "CSRF protection for the web framework Iron"
repository = "https://github.com/heartsucker/iron-csrf"
readme = "README.md"
license = "MIT"
keywords = [ "iron", "csrf", "web", "security" ]

[dependencies]
chrono = { version = "^0.3", features = [ "rustc-serialize" ] }
hyper = "^0.10"
iron = "^0.5"
ring = "^0.6"
rustc-serialize = "^0.3"
untrusted = "^0.3"
urlencoded = "^0.5"

[lib]
name = "iron_csrf"
path = "./src/lib.rs"
