[package]
name = "iron-csrf"
version = "0.0.8"
authors = [ "heartsucker <heartsucker@autistici.org>" ]
description = "CSRF protection for the web framework Iron"
homepage = "https://github.com/heartsucker/iron-csrf"
repository = "https://github.com/heartsucker/iron-csrf"
documentation = "https://docs.rs/iron-csrf"
readme = "README.md"
license = "MIT"
keywords = [ "iron", "csrf", "web", "security" ]
categories = [ "web-programming::http-server", "authentication", "cryptography" ]
travis-ci = { repository = "https://github.com/heartsucker/iron-csrf", branch = "master" }

[lib]
name = "iron_csrf"
path = "./src/lib.rs"

[dependencies]
chrono = "^0.3"
cookie = { version = "^0.6", features = [ "percent-encode" ] }
hyper = "^0.10"
iron = "^0.5"
protobuf = "^1.2"
ring = "^0.7"
rustc-serialize = "^0.3"
time = "^0.1"
untrusted = "^0.3"
urlencoded = "^0.5"

[dev-dependencies]
iron-test = "^0.5"
urlencoding = "^0.2"
