[package]
name = "iron-csrf"
version = "0.0.1"
authors = ["heartsucker <heartsucker@autistici.org>"]
description = "CSRF protection for the web framework Iron"
repository = "https://github.com/heartsucker/iron-csrf"
readme = "README.md"
license-file = "LICENSE"
keywords = [ "iron", "csrf", "web", "security" ]

[dependencies]
iron = "^0.5"
ring = "^0.6"
rustc-serialize = "^0.3"
time = "^0.1"
untrusted = "^0.3"
urlencoded = "^0.5"

[lib]
name = "iron_csrf"
path = "./src/lib.rs"
